env:
  # TERM env customization.
  #
  # If this property is not set, alacritty will set it to xterm-256color.
  #
  # Note that some xterm terminfo databases don't declare support for italics.
  # You can verify this by checking for the presence of `smso` and `sitm` in
  # `infocmp xterm-256color`.
  TERM: xterm-256color
window:
  # Window dimensions in character columns and lines
  # (changes require restart)
  dimensions:
    columns: 160
    lines: 48

  # Adds this many blank pixels of padding around the window
  # Units are physical pixels; this is not DPI aware.
  # (change requires restart)
  padding:
    x: 2
    y: 2

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: false

  dynamic_title: true

  # Background opacity
  opacity: 0.8

font:
  normal:
    family: "Hack"
    style: Bold

  size: 8
draw_bold_text_with_bright_colors: true

colors:
  # Default colors
  primary:
    background: '#000000'
    foreground: '0xcbe3e7'

  # Normal colors
  normal:
    black:   '0x10100E'
    red:     '0xC40233'
    green:   '0x009F6B'
    yellow:  '0xFFD700'
    blue:    '0x0087BD'
    magenta: '0x9A4EAE'
    cyan:    '0x20B2AA'
    white:   '0xC6C6C4'

  # Bright colors
  bright:
    black:   '0x696969'
    red:     '0xFF2400'
    green:   '0x03C03C'
    yellow:  '0xFDFF00'
    blue:    '0x007FFF'
    magenta: '0xFF1493'
    cyan:    '0x00CCCC'
    white:   '0xFFFAFA'
selection:
  save_to_clipboard: true 
cursor:
  style:
    shape: Block
    blinking: On
  vi_mode_style: Block
  blink_interval: 750
  unfocused_hollow: true
