[colors.normal]
black = "0x10100E"
blue = "0x3867df"
cyan = "0x20B2AA"
green = "0x09ed01"
magenta = "0x9A4EAE"
red = "0xf50202"
white = "0xffffff"
yellow = "0xdee600"
[colors.primary]
background = "0x{{ $background }}"
foreground = "0x{{ $onAny }}"
