[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x696969"
blue = "0x007FFF"
cyan = "0x00CCCC"
green = "0x03C03C"
magenta = "0xFF1493"
red = "0xFF2400"
white = "0xFFFAFA"
yellow = "0xFDFF00"

[colors.normal]
black = "0x10100E"
blue = "0x0087BD"
cyan = "0x20B2AA"
green = "0x009F6B"
magenta = "0x9A4EAE"
red = "0xC40233"
white = "0xC6C6C4"
yellow = "0xFFD700"

[colors.primary]
background = "#000000"
foreground = "0xcbe3e7"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.normal]
family = "Terminus (TTF)"
style = "Bold"

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.8

[window.dimensions]
columns = 100
lines = 50

[window.padding]
x = 0
y = 0
[cursor]
blink_interval = 100 
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "On"
shape = "Block"
   
