/* app.in.c generated by valac 0.56.17, the Vala compiler
 * generated from app.in.vala, do not modify */

#include <astal.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gio/gio.h>
#include <astal-io.h>
#include <gdk/gdk.h>
#include <gtk/gtk.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_APP (app_get_type ())
#define APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_APP, App))
#define APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_APP, AppClass))
#define IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_APP))
#define IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_APP))
#define APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_APP, AppClass))

typedef struct _App App;
typedef struct _AppClass AppClass;
typedef struct _AppPrivate AppPrivate;
enum  {
	APP_0_PROPERTY,
	APP_NUM_PROPERTIES
};
static GParamSpec* app_properties[APP_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_BAR (bar_get_type ())
#define BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BAR, Bar))
#define BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_BAR, BarClass))
#define IS_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BAR))
#define IS_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_BAR))
#define BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BAR, BarClass))

typedef struct _Bar Bar;
typedef struct _BarClass BarClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _App {
	AstalApplication parent_instance;
	AppPrivate * priv;
};

struct _AppClass {
	AstalApplicationClass parent_class;
};

static gpointer app_parent_class = NULL;
VALA_EXTERN App* app_instance;
App* app_instance = NULL;

VALA_EXTERN GType app_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (App, g_object_unref)
static void app_real_request (AstalApplication* base,
                       const gchar* msg,
                       GSocketConnection* conn,
                       GError** error);
static void app_real_activate (GApplication* base);
VALA_EXTERN Bar* bar_new (GdkMonitor* monitor);
VALA_EXTERN Bar* bar_construct (GType object_type,
                    GdkMonitor* monitor);
VALA_EXTERN GType bar_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Bar, g_object_unref)
static gint app_main (gchar** args,
               gint args_length1);
VALA_EXTERN App* app_new (void);
VALA_EXTERN App* app_construct (GType object_type);
static void app_finalize (GObject * obj);
static GType app_get_type_once (void);

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result;
#line 1624 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1625 "glib-2.0.vapi"
	result = self;
#line 1625 "glib-2.0.vapi"
	return result;
#line 103 "app.in.c"
}

static void
app_real_request (AstalApplication* base,
                  const gchar* msg,
                  GSocketConnection* conn,
                  GError** error)
{
	App * self;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
#line 4 "app.in.vala"
	self = (App*) base;
#line 4 "app.in.vala"
	g_return_if_fail (msg != NULL);
#line 4 "app.in.vala"
	g_return_if_fail (conn != NULL);
#line 5 "app.in.vala"
	_tmp0_ = string_to_string (msg);
#line 5 "app.in.vala"
	_tmp1_ = g_strconcat (_tmp0_, "\n", NULL);
#line 5 "app.in.vala"
	_tmp2_ = _tmp1_;
#line 5 "app.in.vala"
	g_print ("%s", _tmp2_);
#line 5 "app.in.vala"
	_g_free0 (_tmp2_);
#line 6 "app.in.vala"
	astal_io_write_sock (conn, "ok", NULL, NULL);
#line 134 "app.in.c"
}

static void
app_real_activate (GApplication* base)
{
	App * self;
	gchar* home = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	GList* _tmp2_;
	GList* _tmp3_;
	const gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
#line 9 "app.in.vala"
	self = (App*) base;
#line 10 "app.in.vala"
	_tmp0_ = g_getenv ("HOME");
#line 10 "app.in.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 10 "app.in.vala"
	home = _tmp1_;
#line 11 "app.in.vala"
	_tmp2_ = astal_application_get_monitors ((AstalApplication*) self);
#line 11 "app.in.vala"
	_tmp3_ = _tmp2_;
#line 161 "app.in.c"
	{
		GList* mon_collection = NULL;
		GList* mon_it = NULL;
#line 11 "app.in.vala"
		mon_collection = _tmp3_;
#line 11 "app.in.vala"
		for (mon_it = mon_collection; mon_it != NULL; mon_it = mon_it->next) {
#line 169 "app.in.c"
			GdkMonitor* mon = NULL;
#line 11 "app.in.vala"
			mon = (GdkMonitor*) mon_it->data;
#line 173 "app.in.c"
			{
				GdkMonitor* _tmp4_;
				Bar* _tmp5_;
				Bar* _tmp6_;
#line 12 "app.in.vala"
				_tmp4_ = mon;
#line 12 "app.in.vala"
				_tmp5_ = bar_new (_tmp4_);
#line 12 "app.in.vala"
				g_object_ref_sink (_tmp5_);
#line 12 "app.in.vala"
				_tmp6_ = _tmp5_;
#line 12 "app.in.vala"
				gtk_application_add_window ((GtkApplication*) self, (GtkWindow*) _tmp6_);
#line 12 "app.in.vala"
				_g_object_unref0 (_tmp6_);
#line 190 "app.in.c"
			}
		}
#line 11 "app.in.vala"
		(mon_collection == NULL) ? NULL : (mon_collection = (g_list_free (mon_collection), NULL));
#line 195 "app.in.c"
	}
#line 15 "app.in.vala"
	_tmp7_ = home;
#line 15 "app.in.vala"
	_tmp8_ = g_strconcat (_tmp7_, "/.config/ags/style.css", NULL);
#line 15 "app.in.vala"
	_tmp9_ = _tmp8_;
#line 15 "app.in.vala"
	astal_application_apply_css ((AstalApplication*) self, _tmp9_, FALSE);
#line 15 "app.in.vala"
	_g_free0 (_tmp9_);
#line 9 "app.in.vala"
	_g_free0 (home);
#line 209 "app.in.c"
}

static gchar*
_vala_g_strjoinv (const gchar* separator,
                  gchar** str_array,
                  gint str_array_length1)
{
	gboolean _tmp0_ = FALSE;
	gchar* result;
#line 1251 "glib-2.0.vapi"
	if (separator == NULL) {
#line 1252 "glib-2.0.vapi"
		separator = "";
#line 223 "app.in.c"
	}
#line 1254 "glib-2.0.vapi"
	if (str_array != NULL) {
#line 227 "app.in.c"
		gboolean _tmp1_ = FALSE;
#line 1254 "glib-2.0.vapi"
		if (str_array_length1 > 0) {
#line 1254 "glib-2.0.vapi"
			_tmp1_ = TRUE;
#line 233 "app.in.c"
		} else {
			gboolean _tmp2_ = FALSE;
#line 1254 "glib-2.0.vapi"
			if (str_array_length1 == -1) {
#line 238 "app.in.c"
				const gchar* _tmp3_;
#line 1254 "glib-2.0.vapi"
				_tmp3_ = str_array[0];
#line 1254 "glib-2.0.vapi"
				_tmp2_ = _tmp3_ != NULL;
#line 244 "app.in.c"
			} else {
#line 1254 "glib-2.0.vapi"
				_tmp2_ = FALSE;
#line 248 "app.in.c"
			}
#line 1254 "glib-2.0.vapi"
			_tmp1_ = _tmp2_;
#line 252 "app.in.c"
		}
#line 1254 "glib-2.0.vapi"
		_tmp0_ = _tmp1_;
#line 256 "app.in.c"
	} else {
#line 1254 "glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 260 "app.in.c"
	}
#line 1254 "glib-2.0.vapi"
	if (_tmp0_) {
#line 264 "app.in.c"
		gint i = 0;
		gsize len = 0UL;
		gint _tmp16_;
		gint _tmp17_;
		const gchar* res = NULL;
		void* _tmp18_;
		const gchar* _tmp19_ = NULL;
		const gchar* _tmp20_;
		void* ptr = NULL;
		const gchar* _tmp22_;
		void* _tmp23_;
		const gchar* _tmp33_;
#line 1256 "glib-2.0.vapi"
		len = (gsize) 1;
#line 279 "app.in.c"
		{
			gboolean _tmp4_ = FALSE;
#line 1257 "glib-2.0.vapi"
			i = 0;
#line 1257 "glib-2.0.vapi"
			_tmp4_ = TRUE;
#line 1257 "glib-2.0.vapi"
			while (TRUE) {
#line 288 "app.in.c"
				gboolean _tmp6_ = FALSE;
				gboolean _tmp7_ = FALSE;
				gint _tmp10_ = 0;
				const gchar* _tmp11_;
#line 1257 "glib-2.0.vapi"
				if (!_tmp4_) {
#line 295 "app.in.c"
					gint _tmp5_;
#line 1257 "glib-2.0.vapi"
					_tmp5_ = i;
#line 1257 "glib-2.0.vapi"
					i = _tmp5_ + 1;
#line 301 "app.in.c"
				}
#line 1257 "glib-2.0.vapi"
				_tmp4_ = FALSE;
#line 1257 "glib-2.0.vapi"
				if (str_array_length1 != -1) {
#line 1257 "glib-2.0.vapi"
					_tmp7_ = i < str_array_length1;
#line 309 "app.in.c"
				} else {
#line 1257 "glib-2.0.vapi"
					_tmp7_ = FALSE;
#line 313 "app.in.c"
				}
#line 1257 "glib-2.0.vapi"
				if (_tmp7_) {
#line 1257 "glib-2.0.vapi"
					_tmp6_ = TRUE;
#line 319 "app.in.c"
				} else {
					gboolean _tmp8_ = FALSE;
#line 1257 "glib-2.0.vapi"
					if (str_array_length1 == -1) {
#line 324 "app.in.c"
						const gchar* _tmp9_;
#line 1257 "glib-2.0.vapi"
						_tmp9_ = str_array[i];
#line 1257 "glib-2.0.vapi"
						_tmp8_ = _tmp9_ != NULL;
#line 330 "app.in.c"
					} else {
#line 1257 "glib-2.0.vapi"
						_tmp8_ = FALSE;
#line 334 "app.in.c"
					}
#line 1257 "glib-2.0.vapi"
					_tmp6_ = _tmp8_;
#line 338 "app.in.c"
				}
#line 1257 "glib-2.0.vapi"
				if (!_tmp6_) {
#line 1257 "glib-2.0.vapi"
					break;
#line 344 "app.in.c"
				}
#line 1258 "glib-2.0.vapi"
				_tmp11_ = str_array[i];
#line 1258 "glib-2.0.vapi"
				if (_tmp11_ != NULL) {
#line 350 "app.in.c"
					const gchar* _tmp12_;
					gint _tmp13_;
					gint _tmp14_;
#line 1258 "glib-2.0.vapi"
					_tmp12_ = str_array[i];
#line 1258 "glib-2.0.vapi"
					_tmp13_ = strlen ((const gchar*) _tmp12_);
#line 1258 "glib-2.0.vapi"
					_tmp14_ = _tmp13_;
#line 1258 "glib-2.0.vapi"
					_tmp10_ = _tmp14_;
#line 362 "app.in.c"
				} else {
#line 1258 "glib-2.0.vapi"
					_tmp10_ = 0;
#line 366 "app.in.c"
				}
#line 1258 "glib-2.0.vapi"
				len += (gsize) _tmp10_;
#line 370 "app.in.c"
			}
		}
#line 1260 "glib-2.0.vapi"
		if (i == 0) {
#line 375 "app.in.c"
			gchar* _tmp15_;
#line 1261 "glib-2.0.vapi"
			_tmp15_ = g_strdup ("");
#line 1261 "glib-2.0.vapi"
			result = _tmp15_;
#line 1261 "glib-2.0.vapi"
			return result;
#line 383 "app.in.c"
		}
#line 1263 "glib-2.0.vapi"
		str_array_length1 = i;
#line 1264 "glib-2.0.vapi"
		_tmp16_ = strlen ((const gchar*) separator);
#line 1264 "glib-2.0.vapi"
		_tmp17_ = _tmp16_;
#line 1264 "glib-2.0.vapi"
		len += (gsize) (_tmp17_ * (i - 1));
#line 1266 "glib-2.0.vapi"
		_tmp18_ = g_malloc (len);
#line 1266 "glib-2.0.vapi"
		res = _tmp18_;
#line 1267 "glib-2.0.vapi"
		_tmp20_ = str_array[0];
#line 1267 "glib-2.0.vapi"
		if (_tmp20_ != NULL) {
#line 401 "app.in.c"
			const gchar* _tmp21_;
#line 1267 "glib-2.0.vapi"
			_tmp21_ = str_array[0];
#line 1267 "glib-2.0.vapi"
			_tmp19_ = (const gchar*) _tmp21_;
#line 407 "app.in.c"
		} else {
#line 1267 "glib-2.0.vapi"
			_tmp19_ = "";
#line 411 "app.in.c"
		}
#line 1267 "glib-2.0.vapi"
		_tmp22_ = res;
#line 1267 "glib-2.0.vapi"
		_tmp23_ = g_stpcpy ((void*) _tmp22_, _tmp19_);
#line 1267 "glib-2.0.vapi"
		ptr = _tmp23_;
#line 419 "app.in.c"
		{
			gboolean _tmp24_ = FALSE;
#line 1268 "glib-2.0.vapi"
			i = 1;
#line 1268 "glib-2.0.vapi"
			_tmp24_ = TRUE;
#line 1268 "glib-2.0.vapi"
			while (TRUE) {
#line 428 "app.in.c"
				void* _tmp26_;
				void* _tmp27_;
				const gchar* _tmp28_ = NULL;
				const gchar* _tmp29_;
				void* _tmp31_;
				void* _tmp32_;
#line 1268 "glib-2.0.vapi"
				if (!_tmp24_) {
#line 437 "app.in.c"
					gint _tmp25_;
#line 1268 "glib-2.0.vapi"
					_tmp25_ = i;
#line 1268 "glib-2.0.vapi"
					i = _tmp25_ + 1;
#line 443 "app.in.c"
				}
#line 1268 "glib-2.0.vapi"
				_tmp24_ = FALSE;
#line 1268 "glib-2.0.vapi"
				if (!(i < str_array_length1)) {
#line 1268 "glib-2.0.vapi"
					break;
#line 451 "app.in.c"
				}
#line 1269 "glib-2.0.vapi"
				_tmp26_ = ptr;
#line 1269 "glib-2.0.vapi"
				_tmp27_ = g_stpcpy (_tmp26_, (const gchar*) separator);
#line 1269 "glib-2.0.vapi"
				ptr = _tmp27_;
#line 1270 "glib-2.0.vapi"
				_tmp29_ = str_array[i];
#line 1270 "glib-2.0.vapi"
				if (_tmp29_ != NULL) {
#line 463 "app.in.c"
					const gchar* _tmp30_;
#line 1270 "glib-2.0.vapi"
					_tmp30_ = str_array[i];
#line 1270 "glib-2.0.vapi"
					_tmp28_ = (const gchar*) _tmp30_;
#line 469 "app.in.c"
				} else {
#line 1270 "glib-2.0.vapi"
					_tmp28_ = "";
#line 473 "app.in.c"
				}
#line 1270 "glib-2.0.vapi"
				_tmp31_ = ptr;
#line 1270 "glib-2.0.vapi"
				_tmp32_ = g_stpcpy (_tmp31_, _tmp28_);
#line 1270 "glib-2.0.vapi"
				ptr = _tmp32_;
#line 481 "app.in.c"
			}
		}
#line 1273 "glib-2.0.vapi"
		_tmp33_ = res;
#line 1273 "glib-2.0.vapi"
		res = NULL;
#line 1273 "glib-2.0.vapi"
		result = (gchar*) _tmp33_;
#line 1273 "glib-2.0.vapi"
		return result;
#line 492 "app.in.c"
	} else {
		gchar* _tmp34_;
#line 1275 "glib-2.0.vapi"
		_tmp34_ = g_strdup ("");
#line 1275 "glib-2.0.vapi"
		result = _tmp34_;
#line 1275 "glib-2.0.vapi"
		return result;
#line 501 "app.in.c"
	}
}

static gint
app_main (gchar** args,
          gint args_length1)
{
	gchar* instance_name = NULL;
	gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	App* _tmp3_ = NULL;
	GError* _inner_error0_ = NULL;
	gint result;
#line 25 "app.in.vala"
	_tmp0_ = g_strdup ("vala");
#line 25 "app.in.vala"
	instance_name = _tmp0_;
#line 27 "app.in.vala"
	_tmp1_ = instance_name;
#line 27 "app.in.vala"
	_tmp2_ = g_strdup (_tmp1_);
#line 27 "app.in.vala"
	_tmp3_ = app_new ();
#line 27 "app.in.vala"
	astal_io_application_set_instance_name ((AstalIOApplication*) _tmp3_, _tmp2_);
#line 27 "app.in.vala"
	_g_free0 (_tmp2_);
#line 27 "app.in.vala"
	_g_object_unref0 (app_instance);
#line 27 "app.in.vala"
	app_instance = _tmp3_;
#line 534 "app.in.c"
	{
		App* _tmp4_;
		App* _tmp5_;
#line 32 "app.in.vala"
		_tmp4_ = app_instance;
#line 32 "app.in.vala"
		astal_io_application_acquire_socket ((AstalIOApplication*) _tmp4_, &_inner_error0_);
#line 32 "app.in.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 544 "app.in.c"
			goto __catch0_g_error;
		}
#line 33 "app.in.vala"
		_tmp5_ = app_instance;
#line 33 "app.in.vala"
		g_application_run ((GApplication*) _tmp5_, (gint) 0, NULL);
#line 551 "app.in.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		gchar* _tmp6_ = NULL;
		const gchar* _tmp7_;
		gchar* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
#line 31 "app.in.vala"
		g_clear_error (&_inner_error0_);
#line 35 "app.in.vala"
		_tmp7_ = instance_name;
#line 35 "app.in.vala"
		_tmp8_ = _vala_g_strjoinv (" ", args, (gint) args_length1);
#line 35 "app.in.vala"
		_tmp9_ = _tmp8_;
#line 35 "app.in.vala"
		_tmp10_ = astal_io_send_message (_tmp7_, _tmp9_, &_inner_error0_);
#line 35 "app.in.vala"
		_tmp11_ = _tmp10_;
#line 35 "app.in.vala"
		_g_free0 (_tmp9_);
#line 35 "app.in.vala"
		_tmp6_ = _tmp11_;
#line 35 "app.in.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 580 "app.in.c"
			goto __finally0;
		}
#line 35 "app.in.vala"
		g_print ("%s", _tmp6_);
#line 31 "app.in.vala"
		_g_free0 (_tmp6_);
#line 587 "app.in.c"
	}
	__finally0:
#line 31 "app.in.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 592 "app.in.c"
		gint _tmp12_ = -1;
#line 31 "app.in.vala"
		_g_free0 (instance_name);
#line 31 "app.in.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 31 "app.in.vala"
		g_clear_error (&_inner_error0_);
#line 31 "app.in.vala"
		return _tmp12_;
#line 602 "app.in.c"
	}
#line 37 "app.in.vala"
	result = 1;
#line 37 "app.in.vala"
	_g_free0 (instance_name);
#line 37 "app.in.vala"
	return result;
#line 610 "app.in.c"
}

int
main (int argc,
      char ** argv)
{
#line 18 "app.in.vala"
	return app_main (argv, argc);
#line 619 "app.in.c"
}

App*
app_construct (GType object_type)
{
	App * self = NULL;
#line 1 "app.in.vala"
	self = (App*) astal_application_construct (object_type);
#line 1 "app.in.vala"
	return self;
#line 630 "app.in.c"
}

App*
app_new (void)
{
#line 1 "app.in.vala"
	return app_construct (TYPE_APP);
#line 638 "app.in.c"
}

static void
app_class_init (AppClass * klass,
                gpointer klass_data)
{
#line 1 "app.in.vala"
	app_parent_class = g_type_class_peek_parent (klass);
#line 1 "app.in.vala"
	((AstalApplicationClass *) klass)->request = (void (*) (AstalApplication*, const gchar*, GSocketConnection*, GError**)) app_real_request;
#line 1 "app.in.vala"
	((GApplicationClass *) klass)->activate = (void (*) (GApplication*)) app_real_activate;
#line 1 "app.in.vala"
	G_OBJECT_CLASS (klass)->finalize = app_finalize;
#line 653 "app.in.c"
}

static void
app_instance_init (App * self,
                   gpointer klass)
{
}

static void
app_finalize (GObject * obj)
{
	App * self;
#line 1 "app.in.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_APP, App);
#line 1 "app.in.vala"
	G_OBJECT_CLASS (app_parent_class)->finalize (obj);
#line 670 "app.in.c"
}

static GType
app_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (AppClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (App), 0, (GInstanceInitFunc) app_instance_init, NULL };
	GType app_type_id;
	app_type_id = g_type_register_static (ASTAL_TYPE_APPLICATION, "App", &g_define_type_info, 0);
	return app_type_id;
}

GType
app_get_type (void)
{
	static volatile gsize app_type_id__once = 0;
	if (g_once_init_enter (&app_type_id__once)) {
		GType app_type_id;
		app_type_id = app_get_type_once ();
		g_once_init_leave (&app_type_id__once, app_type_id);
	}
	return app_type_id__once;
}

