#!/bin/sh
cur=$(hyprctl activeworkspace -j | jq -r '.id')
ids=($(hyprctl workspaces -j | jq -r '.[].id' | sort -g | tr '\n' ' '))
declare -r las=$(hyprctl workspaces -j | jq -r '.[].id' | sort -g | tail -1)
# echo $cur
echo $ids
for i in ${!ids[@]}; do 
	if [ ${ids[$i]} -gt $cur ]; then 
		    echo ${ids[$i]}
		    hyprctl dispatch workspace ${ids[$i]}
		    break
	    else if [ $cur -eq  $las ];then
		    hyprctl dispatch workspace ${ids[0]}
		    break

	    fi
	fi
done


