#!/usr/bin/env bash

## Author : Aditya Shakya (adi1090x)
## Github : @adi1090x
#
## Rofi   : Power Menu
#
## Available Styles
#
## style-1   style-2   style-3   style-4   style-5

# Current Theme
dir="$HOME/.config/rofi/powermenu/type-1"
dir=$(dirname $0)
theme='power'

# CMDs
uptime="`uptime | sed -e 's/up //g'`"
host=`hostname`

# Options
shutdown='Shutdown'
reboot='Reboot'
lock='Lock'
killmbar='Kill mbar'
suspend='Suspend'
logout='Logout'
yes='Yes'
no='No'

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$host" \
		-mesg "Uptime: $uptime" \
		-theme ${dir}/${theme}.rasi
}

# Confirmation CMD
confirm_cmd() {
	rofi -theme-str 'window {location: center; anchor: center; fullscreen: false; width: 250px;}' \
		-theme-str 'mainbox {children: [ "message", "listview" ];}' \
		-theme-str 'listview {columns: 2; lines: 1;}' \
		-theme-str 'element-text {horizontal-align: 0.5;}' \
		-theme-str 'textbox {horizontal-align: 0.5;}' \
		-dmenu \
		-p 'Confirmation' \
		-mesg 'Are you Sure?' \
		-theme ${dir}/${theme}.rasi
}

# Ask for confirmation
confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$lock\n$suspend\n$logout\n$reboot\n$shutdown\n$killmbar" | rofi_cmd
}

# Execute Command
run_cmd() {
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
		if [[ $1 == '--shutdown' ]]; then
			loginctl poweroff
		elif [[ $1 == '--reboot' ]]; then
			loginctl reboot
		elif [[ $1 == '--suspend' ]]; then
			# mpc -q pause
			# amixer set Master mute
			# systemctl suspend
			echo "not implemented"
		elif [[ $1 == '--logout' ]]; then
			hyprctl dispatch exit
		elif [[ $1 == '--killmbar' ]]; then
			killall -9 mbar
			# if [[ "$DESKTOP_SESSION" == 'openbox' ]]; then
			# 	openbox --exit
			# elif [[ "$DESKTOP_SESSION" == 'bspwm' ]]; then
			# 	bspc quit
			# elif [[ "$DESKTOP_SESSION" == 'i3' ]]; then
			# 	i3-msg exit
			# elif [[ "$DESKTOP_SESSION" == 'plasma' ]]; then
			# 	qdbus org.kde.ksmserver /KSMServer logout 0 0 0
			# fi
		fi
	else
		exit 0
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $shutdown)
		run_cmd --shutdown
        ;;
    $reboot)
		run_cmd --reboot
        ;;
    $lock)
	hyprlock
		# if [[ -x '/usr/bin/betterlockscreen' ]]; then
		# 	betterlockscreen -l
		# elif [[ -x '/usr/bin/i3lock' ]]; then
		# 	i3lock
		# fi
        ;;
    $suspend)
		run_cmd --suspend
        ;;
    $logout)
		run_cmd --logout
        ;;
	$killmbar)
		run_cmd --killmbar
		;;
esac
