[colors.bright]
black = "#686868"
blue = "#73d0ff"
cyan = "#95e6cb"
green = "#bae67e"
magenta = "#d4bfff"
red = "#f28779"
white = "#ffffff"
yellow = "#ffd580"

[colors.normal]
black = "#191e2a"
blue = "#6dcbfa"
cyan = "#90e1c6"
green = "#a6cc70"
magenta = "#cfbafa"
red = "#ed8274"
white = "#c7c7c7"
yellow = "#fad07b"

[colors.primary]
foreground = "#eaeaea"

[cursor]
style = "Beam"

[font]
size = 8

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"

[selection]
save_to_clipboard = true

[window]
opacity = 0.9

[window.padding]
x = 2
y = 2
